### ISSUE TITLE
data generation

### ISSUE THREAD

**Issue by zichunxx** [yimingli1998/cdf#1]
Hi, Yiming!

Thanks for your generous sharing! 

I'm trying to understand cdf from scratch with [data_generator.py](https://github.com/yimingli1998/cdf/blob/5e3e62d6e0aee2b640668c71d5b88f1d5e7ee32f/frankaemika/data_generator.py).

However, the `get_whole_body_sdf_batch` function does not include the `return_index` argument, and the code snippet after `else` seems to contain some problems with the handling of return values.

https://github.com/yimingli1998/cdf/blob/5e3e62d6e0aee2b640668c71d5b88f1d5e7ee32f/frankaemika/data_generator.py#L42-L50

**Comment by yimingli1998** [comment]
Hello zichunxx,

Thanks for your attention! Indeed, I have updated the [RDF](https://github.com/yimingli1998/RDF/) library. Could you please try it again?

I would apologize that the code is a bit messy now because I am busy with something else, but I will clean it when I have time. Please feel free to contact me if you encounter any other problems.

Best,
Yiming
